### ISSUE TITLE
жду клиент сракеса

### ISSUE THREAD

**Issue by crashmax-dev** [Di7aK/OpenSpaces#1]
первый нах
![image](https://user-images.githubusercontent.com/15673111/98445145-0da64480-2151-11eb-978e-eca67ec4e503.png)

**Comment by Di7aK** [comment]
![image](https://user-images.githubusercontent.com/15695667/98445192-12aaca00-2138-11eb-9940-228aa1d03b73.png)

**Comment by madiyar** [comment]
фсем здрасти :клоун2

**Comment by Di7aK** [comment]
> фсем здрасти :клоун2

тыхто

**Comment by madiyar** [comment]
> 
> 
> > фсем здрасти :клоун2
> 
> тыхто

MadiyarM

**Comment by Di7aK** [comment]
> > > фсем здрасти :клоун2
> > 
> > 
> > тыхто
> 
> MadiyarM

аткуда тута

**Comment by madiyar** [comment]
> 
> 
> > > > фсем здрасти :клоун2
> > > 
> > > 
> > > тыхто
> > 
> > 
> > MadiyarM
> 
> аткуда тута

тут в поиске искал spaces.ru и нашел через spaces-dev

**Comment by crashmax-dev** [comment]
Срать тута https://t.me/spaces_dev

**Comment by Di7aK** [comment]
> > > > > фсем здрасти :клоун2
> > > > 
> > > > 
> > > > тыхто
> > > 
> > > 
> > > MadiyarM
> > 
> > 
> > аткуда тута
> 
> тут в поиске искал spaces.ru и нашел через spaces-dev

пездиж
