### ISSUE TITLE
Иконки сливаются (светлая тема)

### ISSUE THREAD

**Issue by crashmax-dev** [Di7aK/OpenSpaces#3]
![Screenshot_2020-11-21-17-03-59](https://user-images.githubusercontent.com/15673111/99879330-511bab00-2c47-11eb-8548-27816978da5b.jpeg)

**Comment by Di7aK** [comment]
а ты уверен что они вообще есть

**Comment by crashmax-dev** [comment]
> а ты уверен что они вообще есть

На темной теме же есть, епта
